# -*- coding: utf-8 -*-
"""FCFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vz4fQVWaSdZGO3DAEyls188MmEdTRfdn
"""

def fcfs_scheduling(processes):
    current_time = 0
    gantt_chart = []
    waiting_times = []

    for process_id, burst_time in processes:

        waiting_time = current_time
        waiting_times.append(waiting_time)

        gantt_chart.append(str(current_time))
        gantt_chart.append(process_id)

        current_time += burst_time

    gantt_chart.append(str(current_time))

    avg_waiting_time = sum(waiting_times) / len(processes)

    gantt_chart_str = " ".join(gantt_chart)
    return gantt_chart_str, avg_waiting_time


processes = [('p1', 21), ('p2', 3), ('p3', 6), ('p4', 2)]
gantt_chart, avg_wt = fcfs_scheduling(processes)

print("Gantt Chart:", gantt_chart)
print(f"Average Waiting Time: {avg_wt:.2f}")